# _config.yml
title: Ryan Furuness
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Ryan Furuness, software engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ryanfuruness.com" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown processing
markdown: kramdown
highlighter: rouge

# Header pages
header_pages:
  - about.markdown
  - how-i-work.html